// Code generated by MockGen. DO NOT EDIT.
// Source: pool-connector.go
//
// Generated by this command:
//
//	mockgen -source=pool-connector.go -destination=pool-connector_mock.go -package=postgres
//

// Package postgres is a generated GoMock package.
package postgres

import (
	context "context"
	reflect "reflect"

	pgxpool "github.com/jackc/pgx/v5/pgxpool"
	gomock "go.uber.org/mock/gomock"
)

// MockPoolConnector is a mock of PoolConnector interface.
type MockPoolConnector struct {
	ctrl     *gomock.Controller
	recorder *MockPoolConnectorMockRecorder
	isgomock struct{}
}

// MockPoolConnectorMockRecorder is the mock recorder for MockPoolConnector.
type MockPoolConnectorMockRecorder struct {
	mock *MockPoolConnector
}

// NewMockPoolConnector creates a new mock instance.
func NewMockPoolConnector(ctrl *gomock.Controller) *MockPoolConnector {
	mock := &MockPoolConnector{ctrl: ctrl}
	mock.recorder = &MockPoolConnectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPoolConnector) EXPECT() *MockPoolConnectorMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockPoolConnector) Close(pool *pgxpool.Pool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close", pool)
}

// Close indicates an expected call of Close.
func (mr *MockPoolConnectorMockRecorder) Close(pool any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockPoolConnector)(nil).Close), pool)
}

// Connect mocks base method.
func (m *MockPoolConnector) Connect(ctx context.Context, connString string) (*pgxpool.Pool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect", ctx, connString)
	ret0, _ := ret[0].(*pgxpool.Pool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Connect indicates an expected call of Connect.
func (mr *MockPoolConnectorMockRecorder) Connect(ctx, connString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockPoolConnector)(nil).Connect), ctx, connString)
}

// Ping mocks base method.
func (m *MockPoolConnector) Ping(ctx context.Context, pool *pgxpool.Pool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx, pool)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockPoolConnectorMockRecorder) Ping(ctx, pool any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockPoolConnector)(nil).Ping), ctx, pool)
}
