basePath: /
definitions:
  ping.Resp:
    properties:
      timestamp:
        description: Timestamp is the exact time when the ping response was created.
        type: string
    type: object
  subscription.SubReq:
    properties:
      end_date:
        type: string
      price:
        type: integer
      service_name:
        type: string
      start_date:
        type: string
      user_id:
        type: string
    required:
    - price
    - service_name
    - start_date
    - user_id
    type: object
  subscription.SubResp:
    properties:
      end_date:
        type: string
      id:
        type: integer
      price:
        type: integer
      service_name:
        type: string
      start_date:
        type: string
      user_id:
        type: string
    type: object
  subscription.SubSumResp:
    properties:
      total_price:
        type: integer
    type: object
  subscription.UpdateSubReq:
    properties:
      end_date:
        type: string
      id:
        type: integer
      price:
        type: integer
      service_name:
        type: string
      start_date:
        type: string
      user_id:
        type: string
    type: object
  validation.Resp:
    additionalProperties:
      type: string
    type: object
info:
  contact: {}
  description: Subscription service
  title: Subscription API
  version: "1.0"
paths:
  /ping:
    get:
      operationId: ping
      produces:
      - application/json
      responses:
        "200":
          description: Ping success
          schema:
            $ref: '#/definitions/ping.Resp'
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Ping service
      tags:
      - health
  /subscriptions:
    get:
      description: Get paginated list of subscriptions with optional filters
      operationId: subscription-list
      parameters:
      - description: Page number (1-based)
        in: query
        name: page
        required: true
        type: integer
      - description: 'Items per page (max: 100)'
        in: query
        name: limit
        required: true
        type: integer
      - description: filter by service name
        in: query
        name: service_name
        type: string
      - description: filter by user ID
        in: query
        name: user_id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: List subscriptions
          schema:
            items:
              $ref: '#/definitions/subscription.SubResp'
            type: array
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: List subscriptions
      tags:
      - subscription
    post:
      consumes:
      - application/json
      operationId: create-subscription
      parameters:
      - description: |-
          User ID must be uuid
          Date format: MM-YYYY
        in: body
        name: sub
        required: true
        schema:
          $ref: '#/definitions/subscription.SubReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created subscription
          schema:
            $ref: '#/definitions/subscription.SubResp'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/validation.Resp'
        "404":
          description: Not found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Create subscription
      tags:
      - subscription
  /subscriptions/{id}:
    delete:
      description: Delete by subscription ID.
      operationId: delete-subscription
      parameters:
      - description: Subscription ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: no content
        "400":
          description: Bad request
          schema:
            type: string
        "404":
          description: Not found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Delete subscription
      tags:
      - subscription
    get:
      description: Get by subscription ID.
      operationId: get-subscription
      parameters:
      - description: Subscription ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Subscription
          schema:
            $ref: '#/definitions/subscription.SubResp'
        "400":
          description: Bad request
          schema:
            type: string
        "404":
          description: Not found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Get subscription
      tags:
      - subscription
    patch:
      consumes:
      - application/json
      description: Update by subscription ID.
      operationId: update-subscription
      parameters:
      - description: Subscription ID
        in: path
        name: id
        required: true
        type: string
      - description: Subscription
        in: body
        name: sub
        required: true
        schema:
          $ref: '#/definitions/subscription.UpdateSubReq'
      produces:
      - application/json
      responses:
        "200":
          description: User ID must be uuid
          schema:
            $ref: '#/definitions/subscription.SubResp'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/validation.Resp'
        "404":
          description: Not found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Update subscription
      tags:
      - subscription
  /subscriptions/sum:
    get:
      description: Get total_price of all subscriptions.
      operationId: get-subscription-sum
      parameters:
      - description: 'Date format: MM-YYYY'
        in: query
        name: start_date
        required: true
        type: string
      - description: 'Date format: MM-YYYY'
        in: query
        name: end_date
        required: true
        type: string
      - description: filter by service name
        in: query
        name: service_name
        type: string
      - description: filter by user ID
        in: query
        name: user_id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Subscription sum
          schema:
            $ref: '#/definitions/subscription.SubSumResp'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/validation.Resp'
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Get subscription summa
      tags:
      - subscription
swagger: "2.0"
